//   DUMMY
export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_ERROR = "FETCH_POST_ERROR";

//  SEARCH
export const SEARCH_POST_REQUEST = "SEARCH_POST_REQUEST";
export const SEARCH_POST_SUCCESS = "SEARCH_POST_SUCCESS";
export const SEARCH_POST_ERROR = "SEARCH_POST_ERROR";

// MEASSAGE
export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_ERROR = "FETCH_MESSAGE_ERROR";

// USER
export const FETCH_USERLIST_REQUEST = "FETCH_USERLIST_REQUEST";
export const FETCH_USERLIST_SUCCESS = "FETCH_USERLIST_SUCCESS";
export const FETCH_USERLIST_ERROR = "FETCH_USERLIST_ERROR";
